### ISSUE TITLE
Icon/fanart

### ISSUE THREAD

**Issue by emilsvennesson** [emilsvennesson/kodi-viaplay#1]
The plugin definitely needs an icon and fanart. My own graphical skills are abysmal to say the least, and I don't want to use the official icon as that would imply that this is an officially supported plugin.

@eriksoderblom Seeing as you did some nice work on the Game Pass plugin, would you have any interest in helping out here as well? :)

**Comment by eriksoderblom** [comment]
@emilsvennesson Would something like this be okay for a logo: [http://i.imgur.com/vs7uoOW.png](http://i.imgur.com/vs7uoOW.png), or is it too similar to the official logo?
The colors are from the official viaplay logo and it's also inspired by the Kodi logo.

**Comment by emilsvennesson** [comment]
@eriksoderblom That should be okay! I like it, but I'm not too big of a fan of the Kodi logo.

Thanks a lot for helping out! :grinning:
