### ISSUE TITLE
Viaplay crahses with Linux MINT and Kodi

### ISSUE THREAD

**Issue by Pfupferino** [emilsvennesson/kodi-viaplay#11]
Hello again

Viaplay add-on is crashing when I move between the folders.
I'm using a PC with a Asus H87I-plus mainboard and have the following system:
OS: Linux Mint 18.2 (kernel: Linux 4.8.0-53-generic)
Kodi 17.3 Git:20170525-nogitfound
Viaplay version 1.0.8

the log file is attached.
you may can give me a helping hand to solve the issue.

Tack så mycket!

Hälsningar

[kodi.log.txt](https://github.com/emilsvennesson/kodi-viaplay/files/1189704/kodi.log.txt)

**Comment by emilsvennesson** [comment]
Hi! 

Just for clarification: is it the addon that is crashing or is it Kodi? Also, what do you mean with moving between folders? Your log file doesn't show any signs of crashing.

**Comment by Pfupferino** [comment]
Kodi is crashing.
SVT Play addon is more stable.
I installed now Kodi on W10 and your app is stable again, maybe it was a Linux Mint 18.2 problem

**Comment by emilsvennesson** [comment]
@Pfupferino Can we close this?
