### ISSUE TITLE
How to update inputstream.adaptive 

### ISSUE THREAD

**Issue by sebastiananad** [emilsvennesson/kodi-viaplay#12]
Cant get master branch to install on kodi 17.3

Get a message that inputstream.adaptive 2.0.8  can't be found, how do i get that?

/Sebastian

**Comment by emilsvennesson** [comment]
Hi!

Right now, you need to use the Kodi 18 nightly builds to get an up-to-date version of inputstream.adaptive that is compatible with Viaplay unless you compile it yourself. 17.4 will be released soon and should also ship with an updated version.

**Comment by emilsvennesson** [comment]
Kodi 17.4 has a version of inputstream.adaptive that works with Viaplay. See the last post in #9 for instructions how to get it going.
