### ISSUE TITLE
Can't install git-version

### ISSUE THREAD

**Issue by tuxedojoe** [emilsvennesson/kodi-viaplay#13]
Hi,

Thank you for what seems to be a great add-on for Kodi! Hoping to get it to work.

Installed iso8601 and request (didn't get the links working in the instructions, so I tried these)
http://kodi-addons.club/addon/script.module.iso8601/0.1.11
http://mirrors.kodi.tv/addons/gotham/script.module.requests/

But, when trying to install the kodi-viaplay addon from a zip file, I get this error.
"The depedency on inputstream.adaptive 2.0.8"

How can I get inputstream.adaptive.2.0.8? And did I manage to find the right versions of iso8601 and request?

**Comment by emilsvennesson** [comment]
Hi! Please use English as this issue may be helpful to other, non Swedish speaking people.

You have to enable inputstream.adaptive first by going to My add-ons -> VideoPlayer InputStream -> InputStream Adaptive -> Enable Please note that you also need the Widevine binary in place. I have posted instructions on the bottom of #9.

**Comment by tuxedojoe** [comment]
Thanks, I'll look into it and let you know if it works. Changed the question to english.

Please update the links in the README if my links are the correct version.

**Comment by tuxedojoe** [comment]
That did it! Thank you! And as I thought, awesome add-on!
Would be awesome if the "enable Videoplayer InputStream" would be in the instructions as well.

Have a great day!

**Comment by emilsvennesson** [comment]
Great! I'm working on a module that should make this a lot easier in the future.
