### ISSUE TITLE
Sports works, movies and series not

### ISSUE THREAD

**Issue by Jezze83** [emilsvennesson/kodi-viaplay#14]
Im using raspberry pi 3 and latest libreelec milhouse build. Also my viaplay addon is installed from here github. Problem is: sports only works but movies and series not and i have viaplay total accout. Also adaptive stream and widevine is installed. Here is log:

12:40:46.438 T:1942917136  NOTICE: VideoPlayer::OpenFile: https://vod-dash-cdn2-vp.cdn.viaplay.tv/18e7c1c/V10996-1497879868981.ism/index.mpd?filter=%28FourCC%3D%3D%22AVC1%22%26%26systemBitrate%3C5200000%26%26systemBitrate%3E400000%26%26framerate%3C60%29%7C%7C%28type%3D%3D%22audio%22%26%26%28FourCC%3D%3D%22AACL%22%29%29
12:40:46.439 T:1942917136   DEBUG: OnPlayBackStarted: CApplication::OnPlayBackStarted
12:40:46.439 T:1459426192   DEBUG: Thread VideoPlayer start, auto delete: false
12:40:46.439 T:1459426192  NOTICE: Creating InputStream
12:40:46.440 T:1459426192   DEBUG: ADDON: Dll Initializing - InputStream Adaptive
12:40:46.441 T:1459426192   DEBUG: SECTION:LoadDLL(/usr/lib/kodi/addons/inputstream.adaptive/inputstream.adaptive.so.2.1.8)
12:40:46.441 T:1459426192   DEBUG: Loading: /usr/lib/kodi/addons/inputstream.adaptive/inputstream.adaptive.so.2.1.8
12:40:46.453 T:1546621840   DEBUG: Loading settings for https://vod-dash-cdn2-vp.cdn.viaplay.tv/18e7c1c/V10996-1497879868981.ism/index.mpd?filter=%28FourCC%3D%3D%22AVC1%22%26%26systemBitrate%3C5200000%26%26systemBitrate%3E400000%26%26framerate%3C60%29%7C%7C%28type%3D%3D%22audio%22%26%26%28FourCC%3D%3D%22AACL%22%29%29
12:40:46.455 T:1838150544   DEBUG: CGUIInfoManager::SetCurrentMovie(https://vod-dash-cdn2-vp.cdn.viaplay.tv/18e7c1c/V10996-1497879868981.ism/index.mpd?filter=%28FourCC%3D%3D%22AVC1%22%26%26systemBitrate%3C5200000%26%26systemBitrate%3E400000%26%26framerate%3C60%29%7C%7C%28type%3D%3D%22audio%22%26%26%28FourCC%3D%3D%22AACL%22%29%29)
12:40:46.486 T:1942913936   DEBUG: CAnnouncementManager - Announcement: OnPlay from xbmc
12:40:46.487 T:1942913936   DEBUG: GOT ANNOUNCEMENT, type: 1, from xbmc, message OnPlay
12:40:46.487 T:1942913936   DEBUG: CAnnouncementManager - Announcement: OnChanged from xbmc
12:40:46.487 T:1942913936   DEBUG: GOT ANNOUNCEMENT, type: 1024, from xbmc, message OnChanged
12:40:46.601 T:1459426192    INFO: AddOnLog: InputStream Adaptive: SetVideoResolution (1920 x 1080)
12:40:46.601 T:1459426192   DEBUG: AddOnLog: InputStream Adaptive: Open()
12:40:46.601 T:1459426192   DEBUG: AddOnLog: InputStream Adaptive: found inputstream.adaptive.license_key: [not shown]
12:40:46.601 T:1459426192   DEBUG: AddOnLog: InputStream Adaptive: found inputstream.adaptive.license_type: com.widevine.alpha
12:40:46.601 T:1459426192   DEBUG: AddOnLog: InputStream Adaptive: found inputstream.adaptive.manifest_type: mpd
12:40:46.602 T:1459426192   DEBUG: AddOnLog: InputStream Adaptive: Initial bandwidth: 4000000
12:40:46.603 T:1942917136  NOTICE: m_playbackStarting
12:40:46.603 T:1942917136  NOTICE: StereoscopicsManager::IsPlaying
12:40:46.603 T:1459426192   DEBUG: CAddonSettings[inputstream.adaptive]: loading setting definitions
12:40:46.603 T:1459426192   DEBUG: CAddonSettings[inputstream.adaptive]: trying to load setting definitions from old format...
12:40:46.604 T:1459426192   DEBUG: AddOnLog: InputStream Adaptive: MAXRESOLUTION selected: 0
12:40:46.605 T:1459426192   DEBUG: CAddonSettings[inputstream.adaptive]: loading setting definitions
12:40:46.605 T:1459426192   DEBUG: CAddonSettings[inputstream.adaptive]: trying to load setting definitions from old format...
12:40:46.606 T:1459426192   DEBUG: AddOnLog: InputStream Adaptive: MAXRESOLUTIONSECURE selected: 2
12:40:46.606 T:1459426192   DEBUG: CAddonSettings[inputstream.adaptive]: loading setting definitions
12:40:46.607 T:1459426192   DEBUG: CAddonSettings[inputstream.adaptive]: trying to load setting definitions from old format...
12:40:46.607 T:1459426192   DEBUG: AddOnLog: InputStream Adaptive: STREAMSELECTION selected: 0
12:40:46.608 T:1459426192   DEBUG: CAddonSettings[inputstream.adaptive]: loading setting definitions
12:40:46.608 T:1459426192   DEBUG: CAddonSettings[inputstream.adaptive]: trying to load setting definitions from old format...
12:40:46.611 T:1459426192   DEBUG: CAddonSettings[inputstream.adaptive]: loading setting definitions
12:40:46.611 T:1459426192   DEBUG: CAddonSettings[inputstream.adaptive]: trying to load setting definitions from old format...
12:40:46.612 T:1459426192   DEBUG: AddOnLog: InputStream Adaptive: Searching for decrypters in: /usr/lib/kodi/addons/inputstream.adaptive/
12:40:46.678 T:1942917136   DEBUG: ------ Window Deinit (DialogBusy.xml) ------
12:40:46.699 T:1707742096    INFO: Python script stopped
12:40:46.699 T:1707742096   DEBUG: Thread LanguageInvoker 1707742096 terminating
12:40:46.731 T:1459426192   DEBUG: AddOnLog: InputStream Adaptive: Found decrypter: /usr/lib/kodi/addons/inputstream.adaptive/libssd_wv.so
12:40:46.731 T:1459426192   DEBUG: AddOnLog: InputStream Adaptive: Supported URN: urn:uuid:EDEF8BA9-79D6-4ACE-A3C8-27DCD51D21ED
12:40:46.733 T:1459426192   DEBUG: CurlFile::Open(0x42ec308) https://vod-dash-cdn2-vp.cdn.viaplay.tv/18e7c1c/V10996-1497879868981.ism/index.mpd?filter=%28FourCC%3D%3D%22AVC1%22%26%26systemBitrate%3C5200000%26%26systemBitrate%3E400000%26%26framerate%3C60%29%7C%7C%28type%3D%3D%22audio%22%26%26%28FourCC%3D%3D%22AACL%22%29%29
12:40:46.733 T:1459426192    INFO: easy_acquire - Created session to https://vod-dash-cdn2-vp.cdn.viaplay.tv
12:40:47.019 T:1459426192   ERROR: CCurlFile::FillBuffer - Failed: HTTP returned error 400
12:40:47.030 T:1459426192   ERROR: CCurlFile::Open failed with code 400 for https://vod-dash-cdn2-vp.cdn.viaplay.tv/18e7c1c/V10996-1497879868981.ism/index.mpd?filter=%28FourCC%3D%3D%22AVC1%22%26%26systemBitrate%3C5200000%26%26systemBitrate%3E400000%26%26framerate%3C60%29%7C%7C%28type%3D%3D%22audio%22%26%26%28FourCC%3D%3D%22AACL%22%29%29|acceptencoding=gzip&seekable=0
12:40:47.033 T:1459426192   DEBUG: AddOnLog: InputStream Adaptive: Download https://vod-dash-cdn2-vp.cdn.viaplay.tv/18e7c1c/V10996-1497879868981.ism/index.mpd?filter=%28FourCC%3D%3D%22AVC1%22%26%26systemBitrate%3C5200000%26%26systemBitrate%3E400000%26%26framerate%3C60%29%7C%7C%28type%3D%3D%22audio%22%26%26%28FourCC%3D%3D%22AACL%22%29%29 finished
12:40:47.033 T:1459426192   ERROR: AddOnLog: InputStream Adaptive: Could not open / parse mpdURL (https://vod-dash-cdn2-vp.cdn.viaplay.tv/18e7c1c/V10996-1497879868981.ism/index.mpd?filter=%28FourCC%3D%3D%22AVC1%22%26%26systemBitrate%3C5200000%26%26systemBitrate%3E400000%26%26framerate%3C60%29%7C%7C%28type%3D%3D%22audio%22%26%26%28FourCC%3D%3D%22AACL%22%29%29)
12:40:47.033 T:1459426192   DEBUG: AddOnLog: InputStream Adaptive: Session::~Session()
12:40:47.035 T:1459426192   ERROR: CVideoPlayer::OpenInputStream - error opening [https://vod-dash-cdn2-vp.cdn.viaplay.tv/18e7c1c/V10996-1497879868981.ism/index.mpd?filter=%28FourCC%3D%3D%22AVC1%22%26%26systemBitrate%3C5200000%26%26systemBitrate%3E400000%26%26framerate%3C60%29%7C%7C%28type%3D%3D%22audio%22%26%26%28FourCC%3D%3D%22AACL%22%29%29]
12:40:47.035 T:1459426192  NOTICE: CVideoPlayer::OnExit()
12:40:47.035 T:1459426192   DEBUG: AddOnLog: InputStream Adaptive: Close()
12:40:47.035 T:1459426192   DEBUG: SECTION:UnloadDll(/usr/lib/kodi/addons/inputstream.adaptive/inputstream.adaptive.so.2.1.8)
12:40:47.036 T:1459426192    INFO: ADDON: Dll Destroyed - InputStream Adaptive
12:40:47.036 T:1459426192   DEBUG: Thread VideoPlayer 1459426192 terminating
12:40:47.065 T:1942917136   DEBUG: ------ Window Init (DialogConfirm.xml) ------
12:40:47.119 T:1942917136  NOTICE: m_playbackStarting
12:40:48.103 T:1942917136  NOTICE: Previous line repeats 1 times.
12:40:48.103 T:1942917136   DEBUG: LIRC: Update - NEW at 120229:160 0 KEY_OK devinput (KEY_OK)
12:40:48.103 T:1942917136   DEBUG: HandleKey: 11 (0x0b, obc244) pressed, action is Select
12:40:48.103 T:1942917136  NOTICE: m_playbackStarting
12:40:48.383 T:1942917136  NOTICE: Previous line repeats 1 times.
12:40:48.383 T:1942917136   DEBUG: ------ Window Deinit (DialogConfirm.xml) ------
12:40:48.402 T:1546621840   DEBUG: OnPlayBackStopped: CApplication::OnPlayBackStopped
12:40:48.423 T:1942913936   DEBUG: CAnnouncementManager - Announcement: OnStop from xbmc
12:40:48.423 T:1942913936   DEBUG: GOT ANNOUNCEMENT, type: 1, from xbmc, message OnStop
12:40:48.453 T:1942917136  NOTICE: m_playbackStarting
12:40:48.698 T:1777857424   DEBUG: DoWork - Saving file state for video item plugin://plugin.video.viaplay/?action=play&guid=V10996

**Comment by emilsvennesson** [comment]
Hi! I am failing to reproduce this issue myself. Just to confirm: you are able to play movies and TV shows through their website?

**Comment by noglassess** [comment]
Yes, website works fine with all content. Could be some problem with my kodi build maybe.. I’ll wait out the release for kodi 18 and be back if the problem still occurs! :)

**Comment by Jezze83** [comment]
I got this working. I forgot i had smart dns at my router and thats why it didnt work :whiste:

**Comment by emilsvennesson** [comment]
@Jezze83 Well, that explains the HTTP 400 errors. :-)
