### ISSUE TITLE
Unable to load widevine shared library

### ISSUE THREAD

**Issue by appelgran** [emilsvennesson/kodi-viaplay#15]
I have Viaplay addon on Kodi 17.5 on LibreELEC release: RPi2.arm-8.2.0.1 on Raspberry Pi 3.

I'm getting this error:

> 2685: 20:36:55.349 T:1512043424    ERROR: AddOnLog: InputStream Adaptive: Unable to load widevine shared library (/storage/.kodi/cdm/libwidevinecdm.so)

[01_KODI.log - FULL LOG](https://github.com/emilsvennesson/kodi-viaplay/files/1610163/01_KODI.log)

I installed Viaplay addon from Kodi repo and followed the pop-ups, installed inputstream.adaptive and then getting widevine via a 2 GB chromium(os?) image. I can't play anything so something must have gone wrong.

I found the libwidevinecdm.so file and it is a 7.1 MB file, using `file` on Ubuntu I saw it was for 32-bit arm. I believe my RPi3 is arm64 so I've tried downloading a arm64 livewidevinecdm.so (found one in ubuntu chromium-browser package, just ~400 KB..), tried replace the other with it but the result were the same as before.

**Comment by emilsvennesson** [comment]
Hi! I have posted a temporary solution for this in https://github.com/emilsvennesson/script.module.inputstreamhelper/issues/8.

**Comment by emilsvennesson** [comment]
@appelgran https://github.com/osmc/osmc/issues/420

**Comment by appelgran** [comment]
@emilsvennesson Brilliant! I got it working using your temporary solution.

I also tried reverting the fix and updating LibreELEC from 8.2.0 to 8.2.2 but it did not work. I got the same error again about it being unable to load widevine shared library. Applying the fix in 8.2.2 got it working again.

**Comment by emilsvennesson** [comment]
@appelgran Ah yeah, it looks like the libraries is included in LibreELEC 9+ only. I'm glad you got it working!

**Comment by vixoltrinx** [comment]
Hi, I have a raspbian on a raspberry pi 3. I have installed your add-on and used the "hack" where I substitute line 425 in the .py file. Still, my viaplay doesnt play. 

Can you tell me how to install your add-on and what steps to take to get it to work with my set up? I do not want to use one of the slimmer kodi distros, I want raspbian as os. 

/Christian
