### ISSUE TITLE
Viafree

### ISSUE THREAD

**Issue by dietyyli** [emilsvennesson/kodi-viaplay#17]
Hello. Sorry this is probably wrong place to ask but, is there a plugin for Viafree or does this support Viafree?
Like viafree.fi viafree.se viafree.dk etc.

**Comment by emilsvennesson** [comment]
Retrospect still works afaik. I'm closing this issue as it is unrelated to this add-on,

https://bitbucket.org/basrieter/xbmc-online-tv
