### ISSUE TITLE
Live streams start from the beginning without audio

### ISSUE THREAD

**Issue by psonnosp** [emilsvennesson/kodi-viaplay#22]
Trying to watch the hockey world championship final but when I click to start the game I get a screen with the Viaplay logo and "Standby - a new live event coming up here soon" and after a while the broadcast starts from the beginning with out possibility to fast forward so it becomes live.
And on top of that there's no audio.

Something wrong at my end or is the add-on broken?

**Comment by emilsvennesson** [comment]
Hi! This is something that has to be fixed in inputstream.adaptive.

I will try to get in touch with @peak3d to see if this is anything that can be taken care of. :-)

**Comment by emilsvennesson** [comment]
This is now fixed in the inputstream.adaptive master and will be included in the next version.
