### ISSUE TITLE
Can't get addon to work on Kodi 18 RP 3 B+

### ISSUE THREAD

**Issue by Zaccov** [emilsvennesson/kodi-viaplay#23]
Using Leia build #0630
Installed Viaplay addon from the Kodi Repo but I can't get any content.
Updated it with the master no changes.
Deleted everything and re installed the addon using master from github.
No changes.
Does this addon work with Kodi 18
[log-2018-07-01-11.08.34.zip](https://github.com/emilsvennesson/kodi-viaplay/files/2152758/log-2018-07-01-11.08.34.zip)

**Comment by emilsvennesson** [comment]
@Zaccov Hi! You haven't enabled debug logging in the Kodi settings.

Could you update to the latest Leia build and see if that does anything?

**Comment by Zaccov** [comment]
On my way

**Comment by Zaccov** [comment]
Ok now it looks different. Now it wants me to install widwine

**Comment by Zaccov** [comment]
Still can't see channels though

**Comment by emilsvennesson** [comment]
I'm closing this now because it is now a duplicate of #21.
