### ISSUE TITLE
Live sports/Channels- No playback

### ISSUE THREAD

**Issue by petreee** [emilsvennesson/kodi-viaplay#24]
Hi!

Awesome work with the addon. Since a couple of months ago I can't get live sports and channels to work. When I select a stream it doesn't play. I have tried both Krypton and Leia. Is this a known error?

**Comment by emilsvennesson** [comment]
Hi!

No, this is not a known issue. I need a Kodi debug log to see what's going on.

**Comment by petreee** [comment]
[kodi.log](https://github.com/emilsvennesson/kodi-viaplay/files/2218909/kodi.log)

Here you go :) Btw, now I don't seem to see the channels. I just get the error when I select it. There isn't any live sport events at the moment so I can't try, maybe later if you need it.

**Comment by emilsvennesson** [comment]
The listing should work after 2baf467. Try and see if you're still having playback issues and if you do, hit me up with a new log. :-)

**Comment by petreee** [comment]
Thanks! Progress! I can now see the listing, but the first problem is still there, I press the stream but nothings happens. I can also mention that your other addon, Cmore works like a charm :) 

[kodi.log](https://github.com/emilsvennesson/kodi-viaplay/files/2220323/kodi.log)

**Comment by petreee** [comment]
Yeah, it works with the latest alpha, thanks! Got to be ready when the football season starts you know ;)
