### ISSUE TITLE
Serie A/La Liga

### ISSUE THREAD

**Issue by petreee** [emilsvennesson/kodi-viaplay#25]
(This is actually a request but i didn't find a good place to post)

A new streaming service are apparently going to show Serie A and La Liga this season, according to [THIS](https://www.strivesport.com). 

It would be awesome if you maybe could do a Kodi addon to this service if possible. If not, that's ok :)

**Comment by emilsvennesson** [comment]
Hi! I'm lacking the motivation to take on any more projects on my spare time right now, although I agree it would have been nice to have a Kodi add-on for Strive. Perhaps in the future if no one else beats me to the punch!  :grinning:

I'm closing this because it is unrelated to the Viaplay add-on.
