### ISSUE TITLE
Live streams start from the beginning

### ISSUE THREAD

**Issue by raakanassu** [emilsvennesson/kodi-viaplay#26]
All live streams play from the beginning. I can fast forward, but the stream crashes when I get close to live. For example if a game has been on for 15 minutes when I tune in, I only get a 15 minute broadcast from the beginning.

**Comment by emilsvennesson** [comment]
Hi!

This has been fixed in later versions of inputstream.adaptive. Upgrade to the latest nightly and it should work as expected.

Closing as this is a duplicate of #22.
