### ISSUE TITLE
Missing rio2016 in the main categories for kodi-viaplay

### ISSUE THREAD

**Issue by Z-Runner** [emilsvennesson/kodi-viaplay#3]
Hey it works perfectly, but I'am missing the categori rio2016 in the base menu. I can not figure out why it is not there.

**Comment by emilsvennesson** [comment]
Hi! :smiley: 

Currently, the audio is missing on sports (due to http://trac.kodi.tv/ticket/16670) so I haven't bothered adding support for Rio 2016 seeing as it would be useless for the most of us.

**Comment by Z-Runner** [comment]
Ok! 
But still I wonder why you don't get all the categories from ViaPlay with thet get comand?
Or is the first view in Kodi hard coded?

**Comment by emilsvennesson** [comment]
Nope, but it only lists categories that are equal to 'vod' (8918bf27ca89f9bcef8854b3302e5d12175da8a5). I took a look and Viaplay have tagged the Rio 2016 section with 'rio2016'.
