### ISSUE TITLE
No content in the addon

### ISSUE THREAD

**Issue by JensHKnudsen** [emilsvennesson/kodi-viaplay#31]
Did viaplay change something?
I have no content in the addon now.
Worked fine until this evening 20:00 (CET) 5 may 2019

My platform is : 
RPi3
LibreElec 9.0.1 (Kernel 4.19.230)
Kodi 18.1 Git-Newclock5_18.1-Leia

I'm using viaplay.dk.

Logfile : [kodi.log](https://github.com/emilsvennesson/kodi-viaplay/files/3148729/kodi.log)

Tried : 
 - logging out of viaplay and reactivate.
 - updating the addon (manually) to version 2.1.2.
 - Restarted / Shutdown
But still no content ;-(

When I'm using viaplay app on android or via a webbrowser on a PC it works flawlessly

**Comment by Zaccov** [comment]
Are you using addon from Kodi repo or have you downloaded the master from here? Don't seem to be the same version. The master here works better.

**Comment by JensHKnudsen** [comment]
> Are you using addon from Kodi repo or have you downloaded the master from here? Don't seem to be the same version. The master here works better.

Tried both... as I wrote... 
I manually updated to 2.1.2 (kodi repo only has 2.1.1)

I can post a 3 Mb kodi debug log if it helps ....

**Comment by JensHKnudsen** [comment]
Logfile added to initial post... 

It does contain errors like  :

[plugin.video.viaplay-2.1.2]: Unsupported page found: viaplay:watchnow

and

ERROR: NEWADDON Unknown Video Info Key "list_title"

**Comment by JensHKnudsen** [comment]
Issue seems to have resolved itself?
I can see programs again so the issue can be closed
