### ISSUE TITLE
Viaplay navigation works, but not playing a video

### ISSUE THREAD

**Issue by zjoasan** [emilsvennesson/kodi-viaplay#33]
Haveing Netflix installed made sure i had widevine installed and inputstream.helper didn't need to do it's job since widevine was allready installed. Viaplay addon starts okey, settigns page then authentiacation via viaplay.se/activate

snipplet of kodi debug log:
[viaplay_kodi.txt](https://github.com/emilsvennesson/kodi-viaplay/files/3522290/viaplay_kodi.txt)

OSMC Vero4k, latest update. viaplay 2.1.2 installed, if more info needed just ping me

**Comment by emilsvennesson** [comment]
I believe this is due to an old version of Widevine. Try updating script.module.inputstreamhelper to version 0.3.5: https://github.com/emilsvennesson/script.module.inputstreamhelper/releases

**Comment by zjoasan** [comment]
Thanks, was just about to close the issue, since i saw there was an updated inputstream.helper. Removed contens of .kodi/cdm and installed the new helper. Worked like a charm.
