### ISSUE TITLE
Account not authorized

### ISSUE THREAD

**Issue by nisak80** [emilsvennesson/kodi-viaplay#4]
Just installed your plugin, and entered my username and password for my Viaplay account.
But when trying to watch a show, I get the message: " Your account is not authorized to watch this content. You will find information on how to upgrade your package on the Viaplay website." Altough when I try to open the same show on my computer og viaplay app on my LG tv this works just fine. 
Is this an known issue? Is there a fix.

Located in Norway. Did also try to switch Country in settings but then I got the message about reigion.

**Comment by emilsvennesson** [comment]
Hi!

No, this it not a known issue. Could you try removing 'cookie_file' located in [userdata](http://kodi.wiki/view/userdata)/addon_data/plugin.video.viaplay and see if that fixes it?

If this does not work, then please attach a debug log (make sure to enable debugging in both Kodi as well as the add-on settings).

**Comment by nisak80** [comment]
Hi emilsvennesson

Thank you for superfast response and help.
Deleting the cookie_file fixed my issue and the plugin is now working perfectly.
Excelent work and again thank you very much.

**Comment by emilsvennesson** [comment]
@nisak80 Can we close this? :-)

**Comment by nisak80** [comment]
Shure, thought it was you that had to close it, that's why I left it open......
