### ISSUE TITLE
Lots of movies and episodes not playable

### ISSUE THREAD

**Issue by unZane** [emilsvennesson/kodi-viaplay#5]
Hi, I cant seem to be able to play any new movies or episodes at all, live sport works... All I can find in the logs are:
[logs](http://pastebin.com/26iJUc0P)

Edited:
Can confirm that downloading master with latest commit [97f1b95](https://github.com/emilsvennesson/kodi-viaplay/commit/97f1b95ef4a5d781fa27761a9963a12acee1c552) fixed my problem

**Comment by emilsvennesson** [comment]
@unZane This was indeed fixed a while ago, but I never got around to cutting another release with the included fix. I've done that now and submitted it for the official repository (https://github.com/xbmc/repo-plugins/pull/788).

Thanks for the report!
