### ISSUE TITLE
"No Valid Stream URL found"

### ISSUE THREAD

**Issue by PlaceboPRS** [emilsvennesson/kodi-viaplay#7]
Hi, starting to get this error more and more for some reason, for example trying to watch Sevilla v Sporting Gijon from yesterday from Finnish Viaplay, and no matter how many times I try I constantly get that error followed by some items couldn't play check log blah blah, I've tried reinstalling the addon, deleting the cookie file, everything. The match plays ok in my browser, it plays ok if I choose Sweden/Denmark in the app but it's only in English on Finnish viaplay so that's the version I wanted most :)

This is my kodi log:

11:56:05.920 T:4992   ERROR: XFILE::CDirectory::GetDirectory - Error getting
11:56:09.512 T:13008   ERROR: Previous line repeats 6 times.
11:56:09.512 T:13008   ERROR: C:\Users\PRS\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\packages\urllib3\connectionpool.py:843: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
                                              InsecureRequestWarning)
11:56:36.046 T:3716   ERROR: Previous line repeats 9 times.
11:56:36.046 T:3716   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.viaplay/?action=play_video&content=sport&streamtype=guid&playid=20419650]
11:56:38.662 T:2856   ERROR: C:\Users\PRS\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\packages\urllib3\connectionpool.py:843: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
                                              InsecureRequestWarning)
11:56:45.145 T:3716   ERROR: Previous line repeats 3 times.
11:56:45.145 T:3716   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.viaplay/?action=play_video&content=sport&streamtype=guid&playid=20419650]

Huge thanks in advance!

Edit: I should add I was on Kodi 17 and upgraded to the latest version yesterday in the hopes it would fix the error which it didn't :(

Edit 2: Sorry I should of course add I'm using it on Windows 10 PC.

**Comment by emilsvennesson** [comment]
Hi! Thanks for the bug report. 

You have cut off the relevant part of the debug log, so please post a full log so I can see the response from the Viaplay API.

**Comment by PlaceboPRS** [comment]
Apologies I thought I included everything, here's a full log started fresh before launching Kodi and then I opened the Viaplay app and tried that specific match two times, both times getting the "No valid Stream URL" Error

17:43:56.454 T:12344  NOTICE: special://profile/ is mapped to: special://masterprofile/
17:43:56.454 T:12344  NOTICE: -----------------------------------------------------------------------
17:43:56.454 T:12344  NOTICE: Starting Kodi (17.1 Git:20170320-fc1619b). Platform: Windows NT x86 32-bit
17:43:56.454 T:12344  NOTICE: Using Release Kodi x32 build
17:43:56.454 T:12344  NOTICE: Kodi compiled Mar 20 2017 by MSVC 190024215 for Windows NT x86 32-bit version 10.0 (0x0A000000)
17:43:56.454 T:12344  NOTICE: Running on Windows 10, kernel: Windows NT x86 64-bit version 10.0
17:43:56.456 T:12344  NOTICE: FFmpeg version/source: ffmpeg-3.1-kodi
17:43:56.456 T:12344  NOTICE: Host CPU: Unknown, 8 cores available
17:43:56.456 T:12344  NOTICE: Desktop Resolution: 1920x1080 32Bit at 60Hz
17:43:56.456 T:12344  NOTICE: Running with administrator rights
17:43:56.459 T:12344  NOTICE: Aero is enabled
17:43:56.459 T:12344  NOTICE: special://xbmc/ is mapped to: C:\Program Files (x86)\Kodi
17:43:56.459 T:12344  NOTICE: special://xbmcbin/ is mapped to: C:\Program Files (x86)\Kodi
17:43:56.459 T:12344  NOTICE: special://xbmcbinaddons/ is mapped to: C:\Program Files (x86)\Kodi/addons
17:43:56.459 T:12344  NOTICE: special://masterprofile/ is mapped to: C:\Users\PRS\AppData\Roaming\Kodi\userdata
17:43:56.459 T:12344  NOTICE: special://home/ is mapped to: C:\Users\PRS\AppData\Roaming\Kodi\
17:43:56.459 T:12344  NOTICE: special://temp/ is mapped to: C:\Users\PRS\AppData\Roaming\Kodi\cache
17:43:56.459 T:12344  NOTICE: special://logpath/ is mapped to: C:\Users\PRS\AppData\Roaming\Kodi\
17:43:56.459 T:12344  NOTICE: The executable running is: C:\Program Files (x86)\Kodi\kodi.exe
17:43:56.468 T:12344  NOTICE: Local hostname: PRS-Win8
17:43:56.468 T:12344  NOTICE: Log File is located: C:\Users\PRS\AppData\Roaming\Kodi\/kodi.log
17:43:56.468 T:12344  NOTICE: -----------------------------------------------------------------------
17:43:56.478 T:12344  NOTICE: load settings...
17:43:56.484 T:12344 WARNING: CSettingString: unknown options filler "timezonecountries" of "locale.timezonecountry"
17:43:56.484 T:12344 WARNING: CSettingString: unknown options filler "timezones" of "locale.timezone"
17:43:56.488 T:12344  NOTICE: No settings file to load (special://xbmc/system/advancedsettings.xml)
17:43:56.489 T:12344  NOTICE: No settings file to load (special://masterprofile/advancedsettings.xml)
17:43:56.489 T:12344  NOTICE: Default Video Player: VideoPlayer
17:43:56.489 T:12344  NOTICE: Default Audio Player: paplayer
17:43:56.489 T:12344  NOTICE: Disabled debug logging due to GUI setting. Level 0.
17:43:56.489 T:12344  NOTICE: Log level changed to "LOG_LEVEL_NORMAL"
17:43:56.489 T:12344  NOTICE: CMediaSourceSettings: loading media sources from special://masterprofile/sources.xml
17:43:56.490 T:12344  NOTICE: Loading player core factory settings from special://xbmc/system/playercorefactory.xml.
17:43:56.491 T:12344  NOTICE: Loaded playercorefactory configuration
17:43:56.491 T:12344  NOTICE: Loading player core factory settings from special://profile/playercorefactory.xml.
17:43:56.492 T:12344 WARNING: CPlayerCoreFactory::GetPlayer(save video url): no such player: save video url
17:43:56.492 T:12344 WARNING: CPlayerCoreFactory::GetPlayer(mpv): no such player: mpv
17:43:56.492 T:12344 WARNING: CPlayerCoreFactory::GetPlayer(play): no such player: play
17:43:56.492 T:12344 WARNING: CPlayerCoreFactory::GetPlayer(vlc): no such player: vlc
17:43:56.492 T:12344 WARNING: CPlayerCoreFactory::GetPlayer(external player): no such player: external player
17:43:56.492 T:12344 WARNING: CPlayerCoreFactory::GetPlayer(video stats): no such player: video stats
17:43:56.492 T:12344 WARNING: CPlayerCoreFactory::GetPlayer(record): no such player: record
17:43:56.492 T:12344 WARNING: CPlayerCoreFactory::GetPlayer(record 30 mins): no such player: record 30 mins
17:43:56.492 T:12344 WARNING: CPlayerCoreFactory::GetPlayer(record 1 hour): no such player: record 1 hour
17:43:56.492 T:12344 WARNING: CPlayerCoreFactory::GetPlayer(record 2 hours): no such player: record 2 hours
17:43:56.492 T:12344 WARNING: CPlayerCoreFactory::GetPlayer(record 3 hours): no such player: record 3 hours
17:43:56.492 T:12344 WARNING: CPlayerCoreFactory::GetPlayer(stream): no such player: stream
17:43:56.492 T:12344 WARNING: CPlayerCoreFactory::GetPlayer(stream 2 hours): no such player: stream 2 hours
17:43:56.492 T:12344 WARNING: CPlayerCoreFactory::GetPlayer(stream 3 hours): no such player: stream 3 hours
17:43:56.492 T:12344 WARNING: CPlayerCoreFactory::GetPlayer(ssh record): no such player: ssh record
17:43:56.492 T:12344 WARNING: CPlayerCoreFactory::GetPlayer(ssh record 30 mins): no such player: ssh record 30 mins
17:43:56.492 T:12344 WARNING: CPlayerCoreFactory::GetPlayer(stream 1 hour): no such player: stream 1 hour
17:43:56.492 T:12344 WARNING: CPlayerCoreFactory::GetPlayer(ssh record 2 hours): no such player: ssh record 2 hours
17:43:56.492 T:12344 WARNING: CPlayerCoreFactory::GetPlayer(ssh record 3 hours): no such player: ssh record 3 hours
17:43:56.492 T:12344 WARNING: CPlayerCoreFactory::GetPlayer(save audio url): no such player: save audio url
17:43:56.492 T:12344  NOTICE: Loaded playercorefactory configuration
17:43:56.506 T:12344  NOTICE: Running database version Addons27
17:43:56.577 T:12344  NOTICE: ADDONS: Using repository repository.xbmc.org
17:43:56.577 T:12344  NOTICE: ADDONS: Using repository xbmc.repo.elmerohueso
17:43:56.577 T:12344  NOTICE: ADDONS: Using repository superrepo.kodi.krypton.all
17:43:56.577 T:12344  NOTICE: ADDONS: Using repository repository.sandmann79.plugins
17:43:56.577 T:12344  NOTICE: ADDONS: Using repository repository.logi85
17:43:56.577 T:12344  NOTICE: ADDONS: Using repository repository.xunitytalk
17:43:56.577 T:12344  NOTICE: ADDONS: Using repository repository.rayw1986
17:43:56.632 T:13628  NOTICE: CAESinkWASAPI::EnumerateDevicesEx: stream type "STREAM_TYPE_DTSHD" on device "1 - PHILIPS FTV (AMD High Definition Audio Device)" seems to be not supported.
17:43:56.632 T:13628  NOTICE: CAESinkWASAPI::EnumerateDevicesEx: stream type "STREAM_TYPE_TRUEHD" on device "1 - PHILIPS FTV (AMD High Definition Audio Device)" seems to be not supported.
17:43:56.632 T:13628  NOTICE: CAESinkWASAPI::EnumerateDevicesEx: stream type "STREAM_TYPE_EAC3" on device "1 - PHILIPS FTV (AMD High Definition Audio Device)" seems to be not supported.
17:43:56.633 T:13628  NOTICE: CAESinkWASAPI::EnumerateDevicesEx: stream type "STREAM_TYPE_DTS" on device "1 - PHILIPS FTV (AMD High Definition Audio Device)" seems to be not supported.
17:43:56.639 T:13628  NOTICE: CAESinkWASAPI::EnumerateDevicesEx: sample rate 192khz on device "1 - PHILIPS FTV (AMD High Definition Audio Device)" seems to be not supported.
17:43:56.642 T:13628  NOTICE: Found 2 Lists of Devices
17:43:56.642 T:13628  NOTICE: Enumerated DIRECTSOUND devices:
17:43:56.642 T:13628  NOTICE:     Device 1
17:43:56.642 T:13628  NOTICE:         m_deviceName      : {EA471C63-0755-4E6A-ABA5-43DD29B4B714}
17:43:56.642 T:13628  NOTICE:         m_displayName     : HDMI - 1 - PHILIPS FTV (AMD High Definition Audio Device)
17:43:56.642 T:13628  NOTICE:         m_displayNameExtra: DIRECTSOUND: 1 - PHILIPS FTV (AMD High Definition Audio Device)
17:43:56.642 T:13628  NOTICE:         m_deviceType      : AE_DEVTYPE_HDMI
17:43:56.642 T:13628  NOTICE:         m_channels        : FL,FR
17:43:56.642 T:13628  NOTICE:         m_sampleRates     : 48000
17:43:56.642 T:13628  NOTICE:         m_dataFormats     : AE_FMT_FLOAT,AE_FMT_RAW
17:43:56.642 T:13628  NOTICE:         m_streamTypes     : STREAM_TYPE_AC3,STREAM_TYPE_DTSHD_CORE,STREAM_TYPE_DTS_1024,STREAM_TYPE_DTS_2048,STREAM_TYPE_DTS_512
17:43:56.642 T:13628  NOTICE:     Device 2
17:43:56.642 T:13628  NOTICE:         m_deviceName      : default
17:43:56.642 T:13628  NOTICE:         m_displayName     : default
17:43:56.642 T:13628  NOTICE:         m_displayNameExtra:
17:43:56.642 T:13628  NOTICE:         m_deviceType      : AE_DEVTYPE_HDMI
17:43:56.642 T:13628  NOTICE:         m_channels        : FL,FR
17:43:56.642 T:13628  NOTICE:         m_sampleRates     : 48000
17:43:56.642 T:13628  NOTICE:         m_dataFormats     : AE_FMT_FLOAT,AE_FMT_RAW
17:43:56.642 T:13628  NOTICE:         m_streamTypes     : STREAM_TYPE_AC3,STREAM_TYPE_DTSHD_CORE,STREAM_TYPE_DTS_1024,STREAM_TYPE_DTS_2048,STREAM_TYPE_DTS_512
17:43:56.642 T:13628  NOTICE: Enumerated WASAPI devices:
17:43:56.642 T:13628  NOTICE:     Device 1
17:43:56.642 T:13628  NOTICE:         m_deviceName      : {EA471C63-0755-4E6A-ABA5-43DD29B4B714}
17:43:56.642 T:13628  NOTICE:         m_displayName     : HDMI - 1 - PHILIPS FTV (AMD High Definition Audio Device)
17:43:56.642 T:13628  NOTICE:         m_displayNameExtra: WASAPI: 1 - PHILIPS FTV (AMD High Definition Audio Device)
17:43:56.642 T:13628  NOTICE:         m_deviceType      : AE_DEVTYPE_HDMI
17:43:56.642 T:13628  NOTICE:         m_channels        : FL,FR
17:43:56.642 T:13628  NOTICE:         m_sampleRates     : 192000,48000,44100,32000
17:43:56.642 T:13628  NOTICE:         m_dataFormats     : AE_FMT_S16NE,AE_FMT_S16LE,AE_FMT_S16BE,AE_FMT_RAW
17:43:56.642 T:13628  NOTICE:         m_streamTypes     : STREAM_TYPE_DTSHD,STREAM_TYPE_TRUEHD,STREAM_TYPE_EAC3,STREAM_TYPE_DTSHD_CORE,STREAM_TYPE_DTS_2048,STREAM_TYPE_DTS_1024,STREAM_TYPE_DTS_512,STREAM_TYPE_AC3
17:43:56.642 T:13628  NOTICE:     Device 2
17:43:56.642 T:13628  NOTICE:         m_deviceName      : default
17:43:56.642 T:13628  NOTICE:         m_displayName     : default
17:43:56.642 T:13628  NOTICE:         m_displayNameExtra:
17:43:56.642 T:13628  NOTICE:         m_deviceType      : AE_DEVTYPE_HDMI
17:43:56.642 T:13628  NOTICE:         m_channels        : FL,FR
17:43:56.642 T:13628  NOTICE:         m_sampleRates     : 192000,48000,44100,32000
17:43:56.642 T:13628  NOTICE:         m_dataFormats     : AE_FMT_S16NE,AE_FMT_S16LE,AE_FMT_S16BE,AE_FMT_RAW
17:43:56.642 T:13628  NOTICE:         m_streamTypes     : STREAM_TYPE_DTSHD,STREAM_TYPE_TRUEHD,STREAM_TYPE_EAC3,STREAM_TYPE_DTSHD_CORE,STREAM_TYPE_DTS_2048,STREAM_TYPE_DTS_1024,STREAM_TYPE_DTS_512,STREAM_TYPE_AC3
17:43:58.625 T:12344  NOTICE: Found screen: Generic PnP Monitor on AMD Radeon (TM) RX 480, adapter 0.
17:43:58.627 T:12344  NOTICE: Primary mode: 1920x1080@ 60.00 - Full Screen
17:43:58.629 T:12344  NOTICE: Additional mode: 640x480@ 24.00 - Full Screen
17:43:58.629 T:12344  NOTICE: Previous line repeats 2 times.
17:43:58.629 T:12344  NOTICE: Additional mode: 640x480@ 50.00 - Full Screen
17:43:58.630 T:12344  NOTICE: Previous line repeats 2 times.
17:43:58.630 T:12344  NOTICE: Additional mode: 640x480@ 59.94 - Full Screen
17:43:58.630 T:12344  NOTICE: Additional mode: 640x480@ 60.00 - Full Screen
17:43:58.631 T:12344  NOTICE: Previous line repeats 2 times.
17:43:58.631 T:12344  NOTICE: Additional mode: 720x480@ 24.00 - Full Screen
17:43:58.631 T:12344  NOTICE: Previous line repeats 2 times.
17:43:58.631 T:12344  NOTICE: Additional mode: 720x480@ 50.00 - Full Screen
17:43:58.632 T:12344  NOTICE: Previous line repeats 2 times.
17:43:58.632 T:12344  NOTICE: Additional mode: 720x480@ 59.94 - Full Screen
17:43:58.632 T:12344  NOTICE: Additional mode: 720x480@ 60.00 - Full Screen
17:43:58.633 T:12344  NOTICE: Previous line repeats 2 times.
17:43:58.633 T:12344  NOTICE: Additional mode: 720x576@ 24.00 - Full Screen
17:43:58.634 T:12344  NOTICE: Previous line repeats 2 times.
17:43:58.634 T:12344  NOTICE: Additional mode: 720x576@ 50.00 - Full Screen
17:43:58.635 T:12344  NOTICE: Previous line repeats 2 times.
17:43:58.635 T:12344  NOTICE: Additional mode: 720x576@ 60.00 - Full Screen
17:43:58.635 T:12344  NOTICE: Previous line repeats 2 times.
17:43:58.635 T:12344  NOTICE: Additional mode: 800x480@ 24.00 - Full Screen
17:43:58.636 T:12344  NOTICE: Previous line repeats 2 times.
17:43:58.636 T:12344  NOTICE: Additional mode: 800x480@ 50.00 - Full Screen
17:43:58.637 T:12344  NOTICE: Previous line repeats 2 times.
17:43:58.637 T:12344  NOTICE: Additional mode: 800x480@ 60.00 - Full Screen
17:43:58.637 T:12344  NOTICE: Previous line repeats 2 times.
17:43:58.637 T:12344  NOTICE: Additional mode: 800x600@ 24.00 - Full Screen
17:43:58.638 T:12344  NOTICE: Previous line repeats 2 times.
17:43:58.638 T:12344  NOTICE: Additional mode: 800x600@ 50.00 - Full Screen
17:43:58.639 T:12344  NOTICE: Previous line repeats 2 times.
17:43:58.639 T:12344  NOTICE: Additional mode: 800x600@ 60.00 - Full Screen
17:43:58.639 T:12344  NOTICE: Previous line repeats 2 times.
17:43:58.639 T:12344  NOTICE: Additional mode: 1024x600@ 24.00 - Full Screen
17:43:58.640 T:12344  NOTICE: Previous line repeats 2 times.
17:43:58.640 T:12344  NOTICE: Additional mode: 1024x600@ 50.00 - Full Screen
17:43:58.641 T:12344  NOTICE: Previous line repeats 2 times.
17:43:58.641 T:12344  NOTICE: Additional mode: 1024x600@ 60.00 - Full Screen
17:43:58.641 T:12344  NOTICE: Previous line repeats 2 times.
17:43:58.641 T:12344  NOTICE: Additional mode: 1024x768@ 24.00 - Full Screen
17:43:58.642 T:12344  NOTICE: Previous line repeats 2 times.
17:43:58.642 T:12344  NOTICE: Additional mode: 1024x768@ 50.00 - Full Screen
17:43:58.643 T:12344  NOTICE: Previous line repeats 2 times.
17:43:58.643 T:12344  NOTICE: Additional mode: 1024x768@ 60.00 - Full Screen
17:43:58.643 T:12344  NOTICE: Previous line repeats 2 times.
17:43:58.643 T:12344  NOTICE: Additional mode: 1152x648@ 50.00 - Full Screen
17:43:58.644 T:12344  NOTICE: Additional mode: 1152x648@ 59.94 - Full Screen
17:43:58.644 T:12344  NOTICE: Additional mode: 1152x648@ 60.00 - Full Screen
17:43:58.644 T:12344  NOTICE: Additional mode: 1280x720@ 50.00 - Full Screen
17:43:58.644 T:12344  NOTICE: Additional mode: 1280x720@ 59.94 - Full Screen
17:43:58.645 T:12344  NOTICE: Additional mode: 1280x720@ 60.00 - Full Screen
17:43:58.645 T:12344  NOTICE: Additional mode: 1280x768@ 24.00 - Full Screen
17:43:58.646 T:12344  NOTICE: Previous line repeats 2 times.
17:43:58.646 T:12344  NOTICE: Additional mode: 1280x768@ 50.00 - Full Screen
17:43:58.646 T:12344  NOTICE: Previous line repeats 2 times.
17:43:58.646 T:12344  NOTICE: Additional mode: 1280x768@ 60.00 - Full Screen
17:43:58.647 T:12344  NOTICE: Previous line repeats 2 times.
17:43:58.647 T:12344  NOTICE: Additional mode: 1280x1024@ 24.00 - Full Screen
17:43:58.648 T:12344  NOTICE: Previous line repeats 2 times.
17:43:58.648 T:12344  NOTICE: Additional mode: 1280x1024@ 50.00 - Full Screen
17:43:58.648 T:12344  NOTICE: Previous line repeats 2 times.
17:43:58.648 T:12344  NOTICE: Additional mode: 1280x1024@ 60.00 - Full Screen
17:43:58.649 T:12344  NOTICE: Previous line repeats 2 times.
17:43:58.649 T:12344  NOTICE: Additional mode: 1360x768@ 24.00 - Full Screen
17:43:58.650 T:12344  NOTICE: Previous line repeats 2 times.
17:43:58.650 T:12344  NOTICE: Additional mode: 1360x768@ 50.00 - Full Screen
17:43:58.650 T:12344  NOTICE: Previous line repeats 2 times.
17:43:58.650 T:12344  NOTICE: Additional mode: 1360x768@ 60.00 - Full Screen
17:43:58.651 T:12344  NOTICE: Previous line repeats 2 times.
17:43:58.651 T:12344  NOTICE: Additional mode: 1366x768@ 24.00 - Full Screen
17:43:58.652 T:12344  NOTICE: Previous line repeats 2 times.
17:43:58.652 T:12344  NOTICE: Additional mode: 1366x768@ 50.00 - Full Screen
17:43:58.653 T:12344  NOTICE: Previous line repeats 2 times.
17:43:58.653 T:12344  NOTICE: Additional mode: 1366x768@ 60.00 - Full Screen
17:43:58.653 T:12344  NOTICE: Previous line repeats 2 times.
17:43:58.653 T:12344  NOTICE: Additional mode: 1400x1050@ 24.00 - Full Screen
17:43:58.654 T:12344  NOTICE: Previous line repeats 2 times.
17:43:58.654 T:12344  NOTICE: Additional mode: 1400x1050@ 50.00 - Full Screen
17:43:58.655 T:12344  NOTICE: Previous line repeats 2 times.
17:43:58.655 T:12344  NOTICE: Additional mode: 1400x1050@ 60.00 - Full Screen
17:43:58.655 T:12344  NOTICE: Previous line repeats 2 times.
17:43:58.655 T:12344  NOTICE: Additional mode: 1600x900@ 24.00 - Full Screen
17:43:58.656 T:12344  NOTICE: Previous line repeats 2 times.
17:43:58.656 T:12344  NOTICE: Additional mode: 1600x900@ 50.00 - Full Screen
17:43:58.657 T:12344  NOTICE: Previous line repeats 2 times.
17:43:58.657 T:12344  NOTICE: Additional mode: 1600x900@ 60.00 - Full Screen
17:43:58.657 T:12344  NOTICE: Previous line repeats 2 times.
17:43:58.657 T:12344  NOTICE: Additional mode: 1680x1050@ 24.00 - Full Screen
17:43:58.658 T:12344  NOTICE: Previous line repeats 2 times.
17:43:58.658 T:12344  NOTICE: Additional mode: 1680x1050@ 50.00 - Full Screen
17:43:58.659 T:12344  NOTICE: Previous line repeats 2 times.
17:43:58.659 T:12344  NOTICE: Additional mode: 1680x1050@ 60.00 - Full Screen
17:43:58.659 T:12344  NOTICE: Previous line repeats 2 times.
17:43:58.659 T:12344  NOTICE: Additional mode: 1776x1000@ 24.00 - Full Screen
17:43:58.660 T:12344  NOTICE: Additional mode: 1776x1000@ 25.00i - Full Screen
17:43:58.660 T:12344  NOTICE: Additional mode: 1776x1000@ 25.00 - Full Screen
17:43:58.660 T:12344  NOTICE: Additional mode: 1776x1000@ 29.97i - Full Screen
17:43:58.660 T:12344  NOTICE: Additional mode: 1776x1000@ 30.00i - Full Screen
17:43:58.661 T:12344  NOTICE: Additional mode: 1776x1000@ 29.97 - Full Screen
17:43:58.661 T:12344  NOTICE: Additional mode: 1776x1000@ 30.00 - Full Screen
17:43:58.661 T:12344  NOTICE: Additional mode: 1776x1000@ 50.00 - Full Screen
17:43:58.661 T:12344  NOTICE: Additional mode: 1776x1000@ 59.94 - Full Screen
17:43:58.662 T:12344  NOTICE: Additional mode: 1776x1000@ 60.00 - Full Screen
17:43:58.662 T:12344  NOTICE: Additional mode: 1920x1080@ 24.00 - Full Screen
17:43:58.662 T:12344  NOTICE: Additional mode: 1920x1080@ 25.00i - Full Screen
17:43:58.662 T:12344  NOTICE: Additional mode: 1920x1080@ 25.00 - Full Screen
17:43:58.662 T:12344  NOTICE: Additional mode: 1920x1080@ 29.97i - Full Screen
17:43:58.663 T:12344  NOTICE: Additional mode: 1920x1080@ 30.00i - Full Screen
17:43:58.663 T:12344  NOTICE: Additional mode: 1920x1080@ 29.97 - Full Screen
17:43:58.663 T:12344  NOTICE: Additional mode: 1920x1080@ 30.00 - Full Screen
17:43:58.663 T:12344  NOTICE: Additional mode: 1920x1080@ 50.00 - Full Screen
17:43:58.664 T:12344  NOTICE: Additional mode: 1920x1080@ 59.94 - Full Screen
17:43:58.664 T:12344  NOTICE: Additional mode: 1920x1080@ 60.00 - Full Screen
17:43:58.664 T:12344  NOTICE: Checking resolution 15
17:43:59.132 T:7700  NOTICE: Running database version Addons27
17:43:59.134 T:7700  NOTICE: Running database version ViewModes6
17:43:59.135 T:7700  NOTICE: Running database version Textures13
17:43:59.138 T:7700  NOTICE: Running database version MyMusic60
17:43:59.141 T:7700  NOTICE: Running database version MyVideos107
17:43:59.143 T:7700  NOTICE: Running database version TV29
17:43:59.144 T:7700  NOTICE: Running database version Epg11
17:43:59.282 T:12344 WARNING: JSONRPC: Could not parse type "Setting.Details.SettingList"
17:43:59.399 T:12344  NOTICE: initialize done
17:43:59.399 T:12344  NOTICE: Running the application...
17:43:59.400 T:12344  NOTICE: starting upnp client
17:43:59.451 T:6280  NOTICE: ES: Starting UDP Event server on port 9777
17:43:59.451 T:6280  NOTICE: UDP: Listening on port 9777 (ipv6 : false)
17:44:02.078 T:2608  NOTICE: [plugin.video.youtube] Startup: detected Krypton (Kodi-17.1), setting DASH_SUPPORT_BUILTIN = False, DASH_SUPPORT_ADDON = True
17:44:02.121 T:6468  NOTICE: Skin Helper Service --> WebService - start helper webservice on port 52307
17:44:02.121 T:5136  NOTICE: Skin Helper Service --> Skin Helper Service version 1.1.3 started
17:44:09.729 T:1960   ERROR: XFILE::CDirectory::GetDirectory - Error getting
17:44:12.554 T:6132   ERROR: Previous line repeats 6 times.
17:44:12.554 T:6132   ERROR: C:\Users\PRS\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\packages\urllib3\connectionpool.py:843: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
                                              InsecureRequestWarning)
17:44:34.870 T:12344   ERROR: Previous line repeats 6 times.
17:44:34.870 T:12344   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.viaplay/?action=play_video&content=sport&streamtype=guid&playid=20419650]
17:44:37.722 T:12772   ERROR: C:\Users\PRS\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\packages\urllib3\connectionpool.py:843: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
                                              InsecureRequestWarning)
17:44:43.887 T:12344   ERROR: Previous line repeats 3 times.
17:44:43.887 T:12344   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.viaplay/?action=play_video&content=sport&streamtype=guid&playid=20419650]
17:44:49.314 T:12344  NOTICE: Storing total System Uptime
17:44:49.314 T:12344  NOTICE: Saving settings
17:44:49.316 T:12344  NOTICE: Saving skin settings
17:44:49.318 T:12344  NOTICE: stop all
17:44:49.318 T:12344  NOTICE: stop player
17:44:49.318 T:12344  NOTICE: ES: Stopping event server
17:44:49.318 T:12344  NOTICE: stopping upnp
17:44:49.469 T:6280  NOTICE: ES: UDP Event server stopped
17:44:49.655 T:12344  NOTICE: clean cached files!
17:44:49.658 T:5136  NOTICE: Skin Helper Service --> Shutdown requested !
17:44:49.672 T:5136  NOTICE: Skin Helper Service --> Skin Helper Service version 1.1.3 stopped
17:44:49.893 T:12344  NOTICE: closing down remote control service
17:44:49.893 T:12344  NOTICE: stopped
17:44:50.094 T:12344  NOTICE: destroy
17:44:50.094 T:12344  NOTICE: unload skin
17:44:50.098 T:12344 WARNING: CGUITextureManager::Cleanup: Having to cleanup texture lists/focus.png
17:44:50.147 T:12344  NOTICE: unload sections
17:44:50.149 T:12344  NOTICE: special://profile/ is mapped to: special://masterprofile/
17:44:50.152 T:12344  NOTICE: application stopped...

**Comment by PlaceboPRS** [comment]
Getting the same error tonight trying to watch Inter v Sampdoria on Viaplay Finland (works fine on Viaplay Sweden).

BTW I'm in Sweden but using SmartDNS with Finland selected for Viaplay so I don't believe it's IP related, I've also tried a Finnish VPN to test previously with no difference.

**Comment by emilsvennesson** [comment]
I'm still not seeing anything from vialib. Are you sure you activated debug logging in the Kodi settings?

**Comment by PlaceboPRS** [comment]
Doh sorry I'm an idiot that was a normal log, this one is with debug turned on, I tried twice to watch the Sevilla v Sporting Gijon match again just in this log and got the error both times.

[kodi.zip](https://github.com/emilsvennesson/kodi-viaplay/files/892775/kodi.zip)

**Comment by PlaceboPRS** [comment]
Hi, just curious if the logs showed up anything or if you've experienced it yourself? During midweek where there were many football matches about 20% or more had this bug and wouldn't play, and I had the issue with the QPR Brighton match last night, fortunately the Viaplay Sweden version was also English so I watched it there instead of from Viaplay Finland.

**Comment by emilsvennesson** [comment]
It looks like Viaplay has started to encrypt some of their HLS sports streams with FairPlay DRM. As far as I know, there's no support for this in ffmpeg/Kodi. While this is sad to see, it was bound to happen at some point. 

One potential 'solution' moving forward is to switch over to MPEG-DASH and libwidevine, similar to what the Netflix plugin uses (https://github.com/asciidisco/plugin.video.netflix). I will be opening a new issue regarding this as I could really need some help from someone that has developed an addon with inputstream.adaptive + libwidevine.

Sorry for the delayed reply!

**Comment by PlaceboPRS** [comment]
Thanks for the reply and investigation, that really sucks, I use the HLS url to download the matches with FFMPEG to watch at my leisure and store match archives and there's no way I know of to do that with the Dash feeds :(

**Comment by PlaceboPRS** [comment]
Virtually nothing plays now due to this error :(

**Comment by PlaceboPRS** [comment]
No sport of any kind plays now, all using DRM I guess :(

**Comment by emilsvennesson** [comment]
Latest git version uses MPEG-DASH and Widevine which solves this issue. 

See https://github.com/emilsvennesson/kodi-viaplay/issues/9 for more information. :-)
