### ISSUE TITLE
Fanart and Icon (Official repository)

### ISSUE THREAD

**Issue by enen92** [emilsvennesson/kodi-viaplay#8]
Dear @emilsvennesson,

Your addon is not showing the icon and the fanart both on kodi or on the addon website. Can you please submit an update to the repository containing at least this commit (https://github.com/emilsvennesson/kodi-viaplay/commit/012df4b995992bec7e2558e80eb87af39df974b8)?

Thanks

**Comment by enen92** [comment]
Also please put the assets tag inside the extension tag. That's likely what is causing issues on the website and kodi itself.

**Comment by emilsvennesson** [comment]
Hi!

Yes, sorry about that. I've been meaning to push out a new release with this fix included but haven't gotten around to it. I'll do it straight away. 

Thanks for reminding me! :-)
