### ISSUE TITLE
MPEG-DASH (inputstream.adaptive) and Widevine CDM

### ISSUE THREAD

**Issue by emilsvennesson** [emilsvennesson/kodi-viaplay#9]
As discussed in #7, Viaplay has started to implement FairPlay DRM on their sports content -- a DRM technology only supported on Apple devices. This is probably going to spread and eventually affect all content, which means that a move away from HLS is inevitable in order for this project to live on.

Viaplay is using MPEG-DASH with Widevine encryption on Google Chrome as well as the Android platform. This is somewhat good news, because it /should/ be possible to implement in a similar way to the Netflix  (https://github.com/asciidisco/plugin.video.netflix) and Sky Go (https://github.com/trummerjo/plugin.video.skygo) add-ons. This is however rather poorly documented and there is not a lot of add-ons using this method to take inspiration from.

I have done some testing but haven't yet been able to figure it out. It's easy to get the MPEG-DASH manifests from the Viaplay API by using 'pcdash' as deviceKey (see https://github.com/emilsvennesson/kodi-viaplay/blob/master/resources/lib/vialib.py#L124). The API will then return an .mpd manifest along with a templated URL for the request to the Widevine license server. However, an additional parameter called '_widevineChallenge' is required to complete the license request that I can't for my life figure out how to generate. 

I'd happily take any help or pointers on this. Feel free to hit me up on #kodi-dev at freenode or by simply responding to this issue. :-)

**Comment by emilsvennesson** [comment]
Well, it turns out that _widevineChallenge is just a base64-encoded string of the challenge that's being generated by the Widevine binary. I am trying to get in touch with @peak3d to iron out some issues regarding the MPD format Viaplay uses.

**Comment by rikardfries** [comment]
Hi, I do run the Magine addon on my kodi and have had great help from several people at k.n. to get it running.
It is not easy to setup but there are descriptions on their webpages. 
I do not have viaplay but would be very interested interested in running/testing the cmore addon.

**Comment by peak3d** [comment]
@emilsvennesson:
- for each encrypted video manifest URL inputstream.adaptive has to know the license-url where to send the license request to.
- you have to use the inputstream.adaptive fork from github.com/liberty-developer as he has the widevine wrapper included.
- pls refer here how to pass the necessary values to inputstream.adaptive using listitem property values:
 https://github.com/liberty-developer/plugin.video.prime_instant/blob/master/default.py#L740-L744
- inputstream.adaptive.license_key is a template you have to define regarding the format your format looks like. I can support finding the correct template if you provide an complete license request to me.
- inputstream.adaptive sends the challenge automatically to the license server if the above mentioned fields are given.

**Comment by emilsvennesson** [comment]
@peak3d Hi and thanks for the comprehensive reply! I have tried this but no matter what I try, I can't seem to get inputstream.adaptive to send any challenge to the license server. Instead, it tries to play the stream which obviously fails because it is encrypted. 

I've also tried with another service (C More) and that works fine, so my guess is that there's some parsing issue with the manifest used my Viaplay that causes it to not detect the encryption properly. I've also tried with kodi-agile and unfortunately it's still behaving the same way there.

Sample MPD format: https://pastebin.com/0j34fQJL
kodi.log on playback attempt: https://pastebin.com/xguBtWs4

Thanks in advance for looking into this!

**Comment by peak3d** [comment]
Yes, you are right, there are 2 issues, one of them is that ContentProtection is currently not supported in representations what leads to the assumption that the stream is not encrypted.

B.t.w: Playready is not supported from looking into the encryption header, only widevine.

**Comment by emilsvennesson** [comment]
@peak3d Ah, I see. Is this something you expect to add support for in the future? :-) Also, would you please care to elaborate what you mean with that only Widevine is supported? When inspecting from Chrome, it's definitely encrypted with Widevine as it's requesting and obtaining the license from a Widevine server.

Regarding the inputstream.adaptive.license_key format: I'm going to have to send a JSON-formatted POST request. Here's a sample:

```
POST /wv/web/ModularDrm?form=json&schema=1.0&httpError=false&token=[EDITED OUT]&account=[EDITED OUT]  HTTP/1.1
Host: widevine.entitlement.theplatform.eu
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:52.0) Gecko/20100101 Firefox/52.0
Accept: */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Content-Length: 2439
Content-Type: text/plain;charset=UTF-8
Origin: https://viaplay.se
Connection: keep-alive

{"getWidevineLicense":{"releasePid":"6_0yhib9WXpY","widevineChallenge":"CAES5AsKigsIARLwCQqzAggCEhVDaHJvbWVDRE0tV2luZG93cy14ODYY3qyOjgUijgIwggEKAoIBAQChp2SyN/oe3bMG20SLvKfCIPL6MwtH9cTL1MvDBlSohXnK1NfQqZLaAK+C5R/er0UtwTx8QQpd47XkLND594UjxhPIeOE9LaU1V0xe3O0Km5zuqa35aKYH9mT3lp2DMcd8PF1K0cqVwwIk+zp1lcujDUfYCuq3TAJmt7boWqkSkGSHAVvDdtmzoS7hg21clsww8Qa5TMJ8NF6o7sfNntqyzHW+AlWT8jmKUxEgZpykDH7pxodGCUl/Fg1buEIrXRK8zwfNSrWOHeCSE5hSPDs1NlLZiuCXCXZ6M04E00lZBmwke3kbBaysQNo4lKGdx0Pa1V/6j5CSygiEa0uzjP8JAgMBAAEo/iESgAI40qYd4AX/ArDuIrtIIFeBbHIG6qb8XscIw1HL1vdK2fiEvOIeBa2gvtknr0nZm1sPVdDB56Nm2P4bzsTkZyFSAe14fHRAfRLJW6r+NlgUQ/AEF53AOuVoNrkLYtiioFwa2aqZNkKEWRp3o4XgeS+/EAwbOXctHP1o2aC2N3zRCFwF+86otvF7tvgbtNpKRv0XdI+7AUrIrd8HaQZHXzT/prXUc4jpc6N05VOAGrlzsEmnUnFxA05EAL6RlJqNjrortn1h+Dbg7YFONztGgXhoZIJNyl4VNHIoyzMIbzRplezkphqA5Ddm5dKU0Q0L1pJ3dNaorWc8u4HzxmxsKu1wGrQFCq4CCAESEIDWitLv5OFYkD1F+8suiocYrqWOjgUijgIwggEKAoIBAQDr2Qct5A12DjupTitPCl2ce2ijnjz9sYDYgzTY4ejtrp6WDLxTYTwYP5aekFESVeFpGQiR2BmGDADgcbetad6M+cRzz2rv3IccTSbGaWncFQf3mRLn0d00+vASDsG9GONYR0vJiOWpmArhoLvz2cIrDxjFXiS70+J7HeTOGXSdcwvvlboT5mmlR4MetggVNQHGcJ25C8oeAcXus9gfm6fkLpivbiizNLjaRQ0cPl4TWBCooHBuumuM0by6zWex7KU+/Cv9EsBgLy31FDL3Bt7B5OksAbd+JX6O5LhbXz68Iij3kfNWPDtQH3tmqHilvZzoTuJGacuNeWaAKRALNMrnAgMBAAEo/iESgAMAsqBvovens6qh7r61e+8brvjPVzMPxvaJbt9ookbyYC8WQXwt/LiRzcfgodSrc0JsTriiEVKInmb64rXIGLzO1BP/v+64q55T3/l0qPliCQt5rRMQeuLbZDbu2VcFwvtvOKskwAkcU8SjXvHjF+ZoMf28Q43KVyOYf80PAa8OGF94dp0eoWuhFqE+ScAECiWsPAcf65YVR5IyFm9AD2svAEYbirbZTpW+aIEpmZVCsZJSkbNrr9lSZxdYMa0ZyVuqzA6v/Aq9srftUtZFLWpcK+iKRMbWfPhKoJEc+Uf2vSkMdek54ELVqW0O0cGkFFf7KL0Kkj2NeIYOPk9kVWpMspbyj7Y/yJZhHVbXPIns/aSiGRqeS3iTEA+q91Ti16twCqRdlfz8hmXlGb5UuR8iY26pUl336qi44swYfbdPB64Zy9DMfih38izi2EtxWm+8h0DjhnRlF7CngPLoztSsVR0PuiKA1+G6Nv6sYCUNM+sjNDojBTEaJiv9BCp8zgkaGwoRYXJjaGl0ZWN0dXJlX25hbWUSBng4Ni0zMhoWCgxjb21wYW55X25hbWUSBkdvb2dsZRoXCgptb2RlbF9uYW1lEglDaHJvbWVDRE0aGAoNcGxhdGZvcm1fbmFtZRIHV2luZG93cxohChR3aWRldmluZV9jZG1fdmVyc2lvbhIJMS40LjguOTAzMggIABAAGAEgARJLCkkKMxIQCBJ84Q4iUN6YGwtiG6QZVxoHdmlhcGxheSIQRzBDSFdOR1RLTEY3SklaQUjj3JWbBhABGhDw14vu2VTVNs3N1sfypGgCGAEghbT5xwUwFRqAAhvrJUa5XgAhy0IWCM/bTRg89EBlrhVVl1cqXZCYqBAZSNSpo7Tv4azpqOk6nGu3zOG7pnJDgosBaznWg8NwgSUVuCy5z8gLoPusGXzuMwd9zkEePlrScNEAaxoOpsInO6NYd0F12fQvGxzGYWa3BihbTIk2A/lI4P4UzxReojPUQB35hrV2zWoA2kQbuSOT3DU8REZn4GGh8nTacfkJCT6c9JklZoGHXgQPZgFdJoGdLkDvYXW313CAkXstaLbeEDJ+CUu8qdl2HU3U+GFFTf/hnGc4apls6kA7Y0bIVYvTEF3FzE2LNkdbcKQdQQeAuMw0MM+iVJpRRanjdB9jbiE="}}
```

releasePid is easily obtained from their API when requesting the stream and widevineChallenge is the challenge base64-encoded. 

Sample response:
```
{
	"getWidevineLicenseResponse": {
		"license": "CAISvAMKKgoQ8NeL7tlU1TbNzdbH8qRoAhIQ8NeL7tlU1TbNzdbH8qRoAhoAIAEoABIoCAEQARgBKAAw/5meAUIZbnVsbC9yZW5ld1dpZGV2aW5lTGljZW5zZRpmEhByRpRLoFQ2fzazJdWw1T7dGlAjgSe0cZR68dOxqT0PXYZoqdoGbfFzhl3ujp+bGyU1SEXjhPmNFw9GpQKMSb2r+BV6FXEBfXEix9iFqap5b40kPc+5gHVFJ2gx15uWSGlFYSABGkoKEAgSfOEOIlDemBsLYhukGVcSEFaTN9GEbUqtgi7QEFTzWi8aIIV/uUsn8XP2zhXTglaVLlPsRCvU03l8fFpaTNnbJFwsIAIoARpKChChB6Rm1bVaKrQBgcbzPnfBEhAvJ9hNq6HFnqNecLFRynJfGiCvQjhjSsvhv1PNkftOkXno435vDOhhPfLXK2hHunOv9iACKAEaSgoQ9UhMjnrJWy2ic8eDyVsNVBIQzDd2eGJNLnebT8qZ1mYGFBogQqi0HBtUpb0wNZ5r1pZHOr1K4kj5Zu1wShLVsXEQZkUgAigBIIW0+ccFOOPclZsGQgxIRENQREFUQQAAAAEaIMq/J/Jgfcg6T7SwZ1cA06RnT1FdDVtdmGkQ6ZuNeebJIoACn0R7pL8h/4+OIcHkMXv8RXkWlviG4AWgr/uZRx1O724L8vE9o9ugGXU/gRgMT4VECeBxOKGRXfnQ7xvhWUdEEs/+fV2VoG3KSoBs2ckS3hZMfL82RiFvBpOkx/vyVQklVIcWd/QLxE8szLC3alpTqUqGHAelQr4G5sleIK5OOsTLVvb8a8JIKyCcTxCOKsd5YNPEx1TIJf+V8cYXzEYOSMPaExKNuGX/1CwJEQuwZl66k9TkqVAnzFZEMa5WG7eBDnGkMJ+152UcdkuASssw9RABmlqOP4SWtQhxWA4EbjJn9dkjf2EG/JPbv3DtQX+h0Z9P+lSfXv5uOaGs99QIcQ=="
	}
}
``

**Comment by peak3d** [comment]
In general inside mp4 container MOOV section you find license information for playready and widevine (because most content provider support both), this can be found in general also in the mpd manifest (wich is not true here, in your mpd manifest there is no hint what type of encryption is supported / required, one has to look into the stream itself)

This note is only to let you know that it is impossible to decrypt the stream with playready drm, only widevine is possible.

Yes, sure, I'll look at it in the next days

**Comment by emilsvennesson** [comment]
@peak3d Great! Thanks a lot. :-)

Do you think something like this would work for the format:
```python
def format_license_post_data(releasePid, wv_challenge):
    post_data = {
        'getWidevineLicense': {
            'releasePid': releasePid,
            'widevineChallenge': base64.b64encode(wv_challenge)
        }
    }

    return json.dumps(post_data)
```
playitem.setProperty('inputstream.adaptive.license_key', LICENSE_URL + '||' + format_license_post_data(releasePid, 'R{SSM}') + |'WHERE_TO_FIND_RESPONSE')

I'm not quite sure how to format the WHERE_TO_FIND_RESPONSE.

**Comment by peak3d** [comment]
```
def format_license_post_data(releasePid, wv_challenge):
    post_data = {
        'getWidevineLicense': {
            'releasePid': releasePid,
            'widevineChallenge': wv_challenge
        }
    }

    return json.dumps(post_data)
```
playitem.setProperty('inputstream.adaptive.license_key', LICENSE_URL + '||' + format_license_post_data(releasePid, 'B{SSM}') + '|JBlicense')

- B{SSM} instructs libssd_wv to base64 encode the challenge
- JBlicense means: the response is a b64encoded JSON string and has to be scanned for "license" key.

**Comment by emilsvennesson** [comment]
@peak3d Thank you!

**Comment by emilsvennesson** [comment]
@peak3d So I tried calling this function within the setProperty for another add-on, but it doesn't actually pass the challenge to the function and instead simply gives me ' 'B{SSM}' as a string. I have worked around this by writing a simple proxy that deals with the communication with the real license server, but it would have been nice to be able to get the challenge data before sending it to the license server somehow.

**Comment by emilsvennesson** [comment]
@rikardfries I've published the code on https://github.com/emilsvennesson/kodi-cmore. Note that you'll need inputstream.adaptive from the agile branch for live streams to work properly.

@peak3d Have you had any chance to look at this yet?

**Comment by peak3d** [comment]
@emilsvennesson should be possible tonight

**Comment by emilsvennesson** [comment]
@peak3d Awesome! I'm looking forward to testing it out. :-)

**Comment by tynor88** [comment]
Hi, let me know if you need some help with testing. Just found the plugin and I'm eager to get the sport playback working (y)

**Comment by PlaceboPRS** [comment]
Would also be happy to test, if the addon can't work with Viaplay then I'll be cancelling my Viaplay membership as football playback through their Android app is utter garbage.

**Comment by emilsvennesson** [comment]
@peak3d I retried this today on the agile branch but I'm still seeing the same thing. I guess it's still a WIP or should I hit you up with a new log?

**Comment by peak3d** [comment]
@emilsvennesson can you pls. pastebinit the mpd file again? The initial link is not valid anymore.
sorry for the delay, the backport agile -> mainline cost a lot of time currently.

**Comment by emilsvennesson** [comment]
@peak3d Ah, no worries! I know you have a lot on your plate. :-)

Here's the MPD: https://pastebin.com/mrp8S804

**Comment by peak3d** [comment]
@emilsvennesson 
> I have worked around this by writing a simple proxy that deals with the communication with the real >license server, but it would have been nice to be able to get the challenge data before sending it to the >license server somehow.

why^^? something missing n the template? The challenge is only valid for this single call.
The next time you request a license the challenge differs.

beside this I added some code for ConenProtection in Representation. Has to be tested.

**Comment by emilsvennesson** [comment]
@peak3d I'm not able to process the Widevine challenge directly in Python, because if I call the function like this: ``playitem.setProperty('inputstream.adaptive.license_key', LICENSE_URL + '||' + format_license_post_data(releasePid, 'B{SSM}') + '|JBlicense')`` wv_challenge in the format_license_post_data function gives me 'B{SSM}' rather than the actual challenge.

Big thanks! I am going to test it out and report back to you!

**Comment by peak3d** [comment]
But you should really not think about a proxy server only because there is something a small issue solved in a few minutes. 

Pls. print out in python what "LICENSE_URL + '||' + format_license_post_data(releasePid, 'B{SSM}') + '|JBlicense'" results to.

**Comment by emilsvennesson** [comment]
@peak3d This is with https://github.com/emilsvennesson/kodi-viaplay/commit/098a50f513e4144c09e582e312d5632f45b5a817 (format_license_data prints out the release_pid and challenge)

````
2:53:05.329 T:140623185172224   DEBUG: [Viaplay]: release_pid: iN46_8dFI_YU
22:53:05.329 T:140623185172224   DEBUG: [Viaplay]: wv_challenge: B{SSM}
````

**Comment by peak3d** [comment]
inputstream.adaptive.license_key is a property attached to the mpd file you pass to kodi / inputstream.adaptive.

B{SSM} will be evaluated in inputstream.adaptive, its a placeholder like %i in a format string.
inputstream.adaptive / libssd_wv will fill the placehlders with the real data and make the license request.

Again, you don't have to deal with the challenge, its all done automagically in inputstream.adaptive.
Simply send the manifest URL with the 3 required listItem properties nd you are done.

**Comment by emilsvennesson** [comment]
@peak3d But what if I have to format the POST data in the challenge like it's done in format_license_post_data, otherwise the challenge request will fail?

I tried with the latest commit in the agile branch and I'm getting an 'Unable to handle decryption. Unsupported!' message in the log now.

kodi.log: https://pastebin.com/rBQNiuTV
mpd file: https://pastebin.com/kthbjPyM

**Comment by peak3d** [comment]
playitem.setProperty('inputstream.adaptive.license_key', LICENSE_URL + '||' + "{ 'getWidevineLicense': { 'releasePid': releasePid, 'widevineChallenge': 'B{SSM}' } }" + '|JBlicense')

something like this, there may be missing some " and + but this^^ is it from concept.

**Comment by emilsvennesson** [comment]
@peak3d I feel like I'm really close now! I'm getting a successful license request, but for some reason inputstream.adaptive fails to find the license in the JSON string. Here's the log snippet: https://pastebin.com/b5TUBsiq

This is the response from the license server:
```
{"getWidevineLicenseResponse":{"license":"CAISoQMKKgoQQMAQpfHqiXs8Bs3VHzBM6RIQQMAQpfHqiXs8Bs3VHzBM6RoAIAEoABINCAEQARgBKAAw/5meARpmEhAuehL2qhKnTexb7QZUA+EgGlCeebVU0eFIAhopKWG+5zRiEsQdIiAvjpmcKghBi0XChkUT2+MIr6o2iZ0d2JxaD8ZyTspj6hgHGnFzTUm9Hybn+rtSp5Mcrhy8dgdn2V7w9SABGkoKEB6IU5Rb5VKgiYlZf65crpcSEIJ42moA7HXGVV2jUq5LHFoaIKNzirECWGOuAtJu/8eYbNwcvYRFVmXKm+YwZH+uDr4HIAIoARpKChANGrWY+LtWQ5h4lAc6AZOXEhBy9fOpZ2WFy2id2R+yv/erGiCaTkwVpZJHLEBmCHnReKG5X/BJtGjM8HvPtFhg8yiwvSACKAEaSgoQUHgq0sMYVB+eP9vTyp6y5hIQCIpTLpY1lvR3t0KvQw4UlBogpnMrai7Nd+y+xDbOB+pwyguBpSKpGTn2RgHYDksSYGkgAigBII6J/sgFOOPclZsGQgxIRENQREFUQQAAAAMaIKlMr1Cezed1Fq/YP9NilAxbcuT5n+18KBjOmXOLzi4RIoACkFpdquMRnCVxSOEfdHUEbv54QdgI0WyrEV8GCp9CcVmv8TQCEkDIbCyw+3ogkfYrxTeciXAhnP2XRQLSpa2FrSr7LX6pv1YueyZ3387rNmrnmWdvYEr2cFU0ptFwuXfYQs9IySWQ14GjAjv17WWc+lfD/7ex1IwFUK3RQ02fI0PDURY0VfM38Z1aXco4R1yzBc7Q9qABsd85NB+DahfXCRtS/WZZW1bTao7/FWEnDSYY/5Qxmqq7iGnWk0gJDuywZ8wjFH/OKgB7EIgv91r11NikRV35rmJWcwYYHUGr3TvLDJUIDcSc//nP+hujEuwOicUHtoLyVGxYiTCe5rnIGg=="}}
```

My license key format: playitem.setProperty('inputstream.adaptive.license_key', stream['license_url'].replace('{widevineChallenge}', 'B{SSM}') + '|||' + 'JBlicense')

**Comment by emilsvennesson** [comment]
@peak3d Also, the new code has introduced the 'Unable to handle decryption. Unsupported!' bug on another MPD sample that works if I revert the last two commits.

Here's the MPD: https://pastebin.com/FjiMsJfc

**Comment by peak3d** [comment]
@emilsvennesson 

print(stream['license_url'].replace('{widevineChallenge}', 'B{SSM}')) pls.
I guess that you may have already separators in it, could it be?

I'll look for the other issue, thx.

**Comment by emilsvennesson** [comment]
@peak3d ```6:50:37.216` T:139983909881600   DEBUG: [plugin.video.viaplay-1.0.8]: https://widevine.entitlement.theplatform.eu/wv/web/ModularDrm/getWidevineLicense?form=json&schema=1.0&httpError=false&_releasePid=0bivYUSLrSPC&token=qBzRHcRUcPsgE1n4VQpmsfBOsHA6APBC&account=http%3A%2F%2Faccess.auth.theplatform.com%2Fdata%2FAccount%2F2361940180&_widevineChallenge=B{SSM}```

Here's a more extensive log: https://pastebin.com/6tSJxyvp

I can confirm that the other issue has been fixed. Thanks! :-)

**Comment by peak3d** [comment]
In ./kodi/cdm/, do you have there 3 files with hex-filenames?
If so, pls zip them and upload.

**Comment by emilsvennesson** [comment]
@peak3d Yes, I've emailed them to you because I'm unsure if they contain any sensible information.

**Comment by peak3d** [comment]
I'll check what happens, but in general it looks already good


Am 20.05.2017 um 19:56 schrieb emilsvennesson:

**Comment by emilsvennesson** [comment]
@peak3d It works! :-D Thanks a lot for all your work, it's much appreciated. 

So TV shows and movies all play flawlessly, but there seems to be some problems with the sports content. I took a quick look at the manifests and they look a bit different to what the other content looked like. The audio plays fine (so I would guess that it's getting decrypted correctly) but I'm getting no picture.

MPD file: https://pastebin.com/fM7QRWQv
kodi.log: https://pastebin.com/LXpbAdRz

**Comment by peak3d** [comment]
Yes, heared of this issue, same at DAZN addon, will look at it tonight

**Comment by emilsvennesson** [comment]
@peak3d Sorry about that! I didn't realize I had enabled component logging for curl... no wonder it was spitting out a lot of data. Here's a new log: https://pastebin.com/hyV0w8wU

I kept ffmpeg component logging enabled but maybe you'd prefer if I disabled that as well?

**Comment by peak3d** [comment]
Because inputstream.adaptive is not using ffmpeg at all (it uses bento4 as demuxer) the ffmpeg lines are not topic related (they are flooding the log when scraping your disk for thumbs / changes).

ffmpeg component logging is the one I have never used and will never use.
video is sometimes important, libCURL as well, but we already jumped over these issues.

From my POV always make without component logging, and I'll ask you for components if necessary.
For now I don't need a new log, the mpd you provided is enough for testing.

**Comment by peak3d** [comment]
This commit: https://github.com/peak3d/inputstream.adaptive/commit/2cdb0c0ab9f1afe367ef22bc3818f2f61d071348

should solve your live-stream issue

**Comment by emilsvennesson** [comment]
I thought I'd give an update on this:

With the latest inputstream.adaptive and kodi-agile, Viaplay (and C More https://github.com/emilsvennesson/kodi-cmore) is working flawlessly in Kodi again. However, as this now requires libwidevine I might have to remove it from the official repository in the future depending on what stance Kodi decides to take on DRM. You can read more about that here: https://forum.kodi.tv/showthread.php?tid=313075

I would recommend people to wait for Kodi 18 to try this out unless you're familiar with building Kodi from source. Right now, patches that haven't been merged into mainline is required which means that you can't use a nightly Kodi build. This will hopefully change in the near future. There's instructions available on the Netflix plugin GitHub page if you want to take on the challenge: https://github.com/asciidisco/plugin.video.netflix/issues/30#issuecomment-290922066

Huge thanks to @peak3d for making this happen. I am going to leave this issue open until it gets easier to actually use this.

**Comment by rikardfries** [comment]
It would be nice to try it but I do not know if it is possible to run on Kodi 17.3 in a windows 10 machine.
Think I have DRM and libwidevine  in place ( from the Previous Magine installation). 
I will give it a try. As soon as I get the time. 
If it is ok with you ?

**Comment by rikardfries** [comment]
It seems to work fine.
The thing that does not work is the texting on the CMORE film channels...

**Comment by emilsvennesson** [comment]
Closing as everything is fully working with Kodi 17.4. Here's some quick instructions:

Download kodi-viaplay from git and install. Follow the instructions below to install the required Widevine library:

# Linux x86/Raspberry Pi
```curl -Ls http://nmacleod.com/public/libreelec/getwidevine.sh | bash```
# Windows
Install a **32-bit** web browser such as Google Chrome, search your system for **libwidevinecdm.dll** and copy the file to **%APPDATA%\Kodi\cdm**.
# Android
Should work out-of-the-box!

**Comment by Rune-C** [comment]
![image](https://user-images.githubusercontent.com/10323328/32413168-f88c0da2-c20b-11e7-82b1-513e5a1ea179.png)

iam really new at this. But i get this fault when use your code . what am i doing wrong
thx for the good work

**Comment by sopparus** [comment]
@Rune-C there are no 64 bit widewine files for arch, I guess you are using odroid c2?
In that case you need to find 32 bit builds of osmc.

I know that 32bit libreelec exist for odroid c2

**Comment by techbliss** [comment]
Hello @emilsvennesson  
im trying myself to fiddle with the widevine server respons.
how do i know what part of the licence reponse is the actual key.

**Comment by deleder** [comment]
This is somewhat off-topic, but would anyone know if the same method could be applied to TV2 Sumo? www.tv2sumo.no

They use DASH, and I think widevine. Would it be technically possible? If someone wants to have a look please speak out.

**Comment by peak3d** [comment]
@deleder If it works in browser, it will work with kodi, too.

**Comment by GianniDPC** [comment]
@emilsvennesson Hi I'm trying to create a Kodi Addon for the Belgian Yelo Play streaming application. 

My POST request seems a bit different as it is base64 encoded, I decoded it and it seems to have a little more information being send than the payload only, I can see that the included payload however looks very close to your wv_challenge, so base64 encoded. What I don't understand is how is this generated? I read you said it was generated by the widevine binary but how can I access that within my application?

If I decode this wv_challenge I get something almost completely unreadable except the string "license.widevine.com."

Decoded it looks something like this (I removed  some information but you get the idea):
`{
  "LatensRegistration": {
    "CustomerName": "",
    "AccountName": "",
    "PortalId": "",
    "FriendlyName": "",
    "DeviceInfo": {
      "FormatVersion": "1",
      "DeviceType": "",
      "OSType": "",
      "OSVersion": "",
      "DRMProvider": "",
      "DRMVersion": "",
      "DRMType": "",
      "DeviceVendor": "",
      "DeviceModel": ""
    }
  },
  "Payload": "CAES2isSWwpZC... // still encoded`

**Comment by deleder** [comment]
> @deleder If it works in browser, it will work with kodi, too.

Thanks for your reply, and sorry for my late answer. What browser are you referring to? TV 2 sumo is browser based streaming service. They use DASH widevine for Chrome, Chromecast and Android. HLS for iOS and Smooth streaming for Smart TV and Playstation.

Thanks!
